version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/resumedb
      - CLIENT_URL=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
